### ISSUE TITLE
consulta de base conbog2019.txt

### ISSUE THREAD

**Issue by edomax** [ospination/Cifra-repartidora-Concejo-Bogota#1]
una consulta, cual es el contenido de esta base conbog2019.txt? como para poder replicar este código
saludos
eduardo

**Comment by ospination** [comment]
Pues la idea que tenia originalmente era ir haciendo un estimado de la repartición de las curules de las pasadas elecciones a concejo a medida que la Registraduría fuera sacando boletines informativos. Entonces simplemente copiaba la información de la pagina de la Registraduría en un .txt llamado "conbog2019" y dejaba que el código lo procesara cada vez que saliera un boletín nuevo.

Ahora para probar que el Notebook funcionara bien utilicé el [resultado histórico que tiene la Registraduria](https://elecciones.registraduria.gov.co:81/esc_elec_2015/99CO/DCO16ZZZZZZZZZZZZZZZ_L1.htm) de las elecciones 2015 para concejo de Bogotá.

Pero gracias a su comentario me doy cuenta que debo actualizar el Notebook y completar el proyecto con los .txt de los resultados de las elecciones 2019

Gracias por el interés.
Cordial saludo

**Comment by edomax** [comment]
Muchas gracias por su pronta respuesta, y la actualización del proyecto. Ahí agregué la base y se ejecutó sin problemas, gracias!
